name: Sync documentation files to Dev Center

on:
  push:
    branches:
    - main

jobs:
  sync-dev-center:
    runs-on: ubuntu-latest
    env:
      SCRIPTS_PATH: scripts/developer_center
      SYNC_MARKDOWN_TARGET_PATH: "buk-webapp/docs/windsurf/mcp-servers"
      SYNC_SSH: ${{ secrets.SYNC_SSH }}
      SYNC_MARKDOWN_FILE_PATTERN: '{src/**/*.md}'
    steps:
    - name: Clone MCPservers repo
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2

    - name: Check documentation changes
      run: |
        result=$(ruby ${{ env.SCRIPTS_PATH }}/check_docs_changes.rb)
        echo "$result" >> $GITHUB_ENV
        if [[ "$result" == "DOC_SYNC=true" ]]; then
          echo "Documentation changes detected. Sync will be performed."
        elif [[ "$result" == "DOC_SYNC=false" ]]; then
          echo "No documentation changes detected. Sync will not be performed."
        fi

    - name: Setup SSH keys and clone buk-developer-center repo
      if: env.DOC_SYNC == 'true'
      run: |
        chmod +x ${{ env.SCRIPTS_PATH }}/setup_ssh.rb
        ${{ env.SCRIPTS_PATH }}/setup_ssh.rb
        git clone git@github.com:bukhr/buk-developer-center.git

    - name: Sync documentation files
      if: env.DOC_SYNC == 'true'
      run: ruby ${{ env.SCRIPTS_PATH }}/sync_docs.rb
